In [1]:
import tensorflow as tf

x1_data = [1, 0, 3, 0, 5]
x2_data = [0, 2, 0, 4, 0]
y_data = [1, 2, 3, 4, 5]

W1 = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

hypothesis = W1 * x1_data + W2 * x2_data + b

cost = tf.reduce_mean(tf.square(hypothesis - y_data))

a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

for step in range(2001):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W1), sess.run(W2), sess.run(b))

0 2.69418 [ 1.51147592] [ 0.99625427] [ 0.38853231]
20 0.00246731 [ 0.96904635] [ 0.96327299] [ 0.11775471]
40 0.000714389 [ 0.98334384] [ 0.98023748] [ 0.06336264]
60 0.000206846 [ 0.99103743] [ 0.98936594] [ 0.03409482]
80 5.98912e-05 [ 0.99517739] [ 0.99427789] [ 0.01834613]
100 1.73409e-05 [ 0.99740499] [ 0.996921] [ 0.00987188]
120 5.02077e-06 [ 0.99860352] [ 0.99834323] [ 0.00531196]
140 1.45377e-06 [ 0.99924868] [ 0.99910849] [ 0.00285837]
160 4.20876e-07 [ 0.9995957] [ 0.9995203] [ 0.00153808]
180 1.21883e-07 [ 0.99978238] [ 0.99974185] [ 0.00082763]
200 3.53165e-08 [ 0.99988294] [ 0.99986106] [ 0.00044537]
220 1.02167e-08 [ 0.99993706] [ 0.99992526] [ 0.0002397]
240 2.96208e-09 [ 0.99996608] [ 0.99995977] [ 0.00012896]
260 8.57801e-10 [ 0.99998182] [ 0.99997836] [  6.94053233e-05]
280 2.4728e-10 [ 0.99999017] [ 0.99998838] [  3.73094153e-05]
300 7.17165e-11 [ 0.99999481] [ 0.99999374] [  2.01289749e-05]
320 2.04551e-11 [ 0.9999972] [ 0.9999966] [  1.08020377e-05]
340 5.92308e-

In [2]:
import tensorflow as tf

x_data = [[1., 0., 3., 0., 5.],
           [0., 2., 0., 4., 0.]]
y_data = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random_uniform([1, 2], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

hypothesis = tf.matmul(W, x_data) + b

cost = tf.reduce_mean(tf.square(hypothesis - y_data))

a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

for step in range(2001):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W), sess.run(b))

0 4.60984 [[ 1.3869884   0.55446208]] [ 1.50951123]
20 0.090602 [[ 0.81242466  0.77744234]] [ 0.71356571]
40 0.026233 [[ 0.89906698  0.88024372]] [ 0.38396293]
60 0.00759556 [[ 0.9456889   0.93556029]] [ 0.20660691]
80 0.00219923 [[ 0.9707756   0.96532559]] [ 0.1111732]
100 0.000636767 [[ 0.98427463  0.98134202]] [ 0.05982127]
120 0.000184371 [[ 0.99153841  0.98996031]] [ 0.03218932]
140 5.33827e-05 [[ 0.99544692  0.99459773]] [ 0.01732079]
160 1.54563e-05 [[ 0.99755001  0.99709308]] [ 0.00932014]
180 4.47545e-06 [[ 0.99868166  0.9984358 ]] [ 0.00501504]
200 1.29573e-06 [[ 0.99929065  0.99915832]] [ 0.00269854]
220 3.75192e-07 [[ 0.99961829  0.99954712]] [ 0.00145211]
240 1.08642e-07 [[ 0.9997946   0.99975634]] [ 0.00078139]
260 3.14524e-08 [[ 0.99988949  0.99986887]] [ 0.00042044]
280 9.10835e-09 [[ 0.99994057  0.99992943]] [ 0.00022622]
300 2.64208e-09 [[ 0.99996799  0.99996203]] [ 0.00012176]
320 7.66468e-10 [[ 0.99998277  0.99997962]] [  6.54790347e-05]
340 2.20351e-10 [[ 0.9999908

In [3]:
import tensorflow as tf

x_data = [[1, 1, 1, 1, 1],
          [1., 0., 3., 0., 5.],
          [0., 2., 0., 4., 0.]]
y_data = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random_uniform([1, 3], -1.0, 1.0))

hypothesis = tf.matmul(W, x_data)

cost = tf.reduce_mean(tf.square(hypothesis - y_data))

a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

for step in range(2001):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W))


0 4.60668 [[ 1.21232533  1.47266555  0.73539311]]
20 0.0518945 [[ 0.54003978  0.85803968  0.83156425]]
40 0.0150256 [[ 0.29059023  0.923612    0.90936625]]
60 0.00435054 [[ 0.15636387  0.95889634  0.95123082]]
80 0.00125966 [[ 0.08413797  0.97788256  0.97375774]]
100 0.000364725 [[ 0.04527387  0.9880988   0.98587924]]
120 0.000105603 [[ 0.02436142  0.99359602  0.99240178]]
140 3.05771e-05 [[ 0.01310867  0.99655402  0.99591148]]
160 8.85292e-06 [[ 0.00705365  0.99814576  0.99779999]]
180 2.56329e-06 [[ 0.0037955   0.99900228  0.99881619]]
200 7.42327e-07 [[ 0.00204237  0.9994632   0.99936301]]
220 2.14895e-07 [[ 0.00109897  0.99971116  0.99965727]]
240 6.22307e-08 [[  5.91391989e-04   9.99844551e-01   9.99815583e-01]]
260 1.80253e-08 [[  3.18235892e-04   9.99916494e-01   9.99900758e-01]]
280 5.21975e-09 [[  1.71198379e-04   9.99954998e-01   9.99946594e-01]]
300 1.51288e-09 [[  9.21005994e-05   9.99975801e-01   9.99971271e-01]]
320 4.36196e-10 [[  4.95523964e-05   9.99987066e-01   9.9998

In [1]:
import tensorflow as tf
import numpy as np
import os

# script_dir = os.path.dirname(os.path.abspath(__file__))
script_dir = os.getcwd()
train_data = np.loadtxt(script_dir + '/data/train.txt', unpack=True, dtype='float32')

x_data = train_data[0:-1]
y_data = train_data[-1]

print(x_data)
print(y_data)

W = tf.Variable(tf.random_uniform([1, len(x_data)], -5.0, 5.0))

hypothesis = tf.matmul(W, x_data)

cost = tf.reduce_mean(tf.square(hypothesis - y_data))

a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

for step in range(2001):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W))

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  3.  0.  5.]
 [ 0.  2.  0.  4.  0.]]
[ 1.  2.  3.  4.  5.]
0 11.909 [[-0.30547565 -0.10352874  0.36513615]]
20 0.00126301 [[ 0.08424933  0.97785175  0.97372282]]
40 0.000365696 [[ 0.04533393  0.988083    0.98586053]]
60 0.000105884 [[ 0.02439376  0.99358749  0.99239171]]
80 3.06574e-05 [[ 0.01312605  0.99654949  0.99590605]]
100 8.87682e-06 [[ 0.00706304  0.99814337  0.99779707]]
120 2.57029e-06 [[ 0.00380059  0.99900103  0.99881464]]
140 7.44211e-07 [[ 0.002045    0.99946237  0.99936217]]
160 2.15401e-07 [[ 0.0011004   0.99971074  0.9996568 ]]
180 6.23611e-08 [[  5.92154451e-04   9.99844313e-01   9.99815285e-01]]
200 1.80578e-08 [[  3.18645383e-04   9.99916255e-01   9.99900579e-01]]
220 5.22563e-09 [[  1.71488660e-04   9.99954939e-01   9.99946475e-01]]
240 1.51433e-09 [[  9.22907711e-05   9.99975681e-01   9.99971211e-01]]
260 4.39312e-10 [[  4.96662979e-05   9.99986947e-01   9.99984503e-01]]
280 1.28568e-10 [[  2.67781143e-05   9.99992967e-01   9.99991