In [1]:
import tensorflow as tf
import numpy as np
import os

# script_dir = os.path.dirname(os.path.abspath(__file__))
script_dir = os.getcwd()
train_data = np.loadtxt(script_dir + '/data/NeuralNetwork.txt', unpack=True, dtype='float')
x_data = np.transpose(train_data[0:-1])
y_data = np.reshape(train_data[-1:], (4, 1))

print(x_data)
print(y_data)

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([2, 5], -1., 1.))
W2 = tf.Variable(tf.random_uniform([5, 5], -1., 1.))
W3 = tf.Variable(tf.random_uniform([5, 4], -1., 1.))
W4 = tf.Variable(tf.random_uniform([4, 1], -1., 1.))

b1 = tf.Variable(tf.random_uniform([5], -1., 1.))
b2 = tf.Variable(tf.random_uniform([5], -1., 1.))
b3 = tf.Variable(tf.random_uniform([4], -1., 1.))
b4 = tf.Variable(tf.random_uniform([1], -1., 1.))

L2 = tf.nn.relu(tf.matmul(X, W1) + b1)
L3 = tf.nn.relu(tf.matmul(L2, W2) + b2)
L4 = tf.nn.relu(tf.matmul(L3, W3) + b3)

hypothesis = tf.sigmoid(tf.matmul(L4, W4) + b4)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

learning_rate = 0.1
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)

for step in range(10000):
    sess.run(train, feed_dict={X: x_data, Y: y_data})

    if step % 200 == 0:
        print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W1), sess.run(W2))

correct_prediction = tf.equal(tf.floor(hypothesis + 0.5), Y)

accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

print(sess.run([hypothesis, tf.floor(hypothesis + 0.5), correct_prediction], feed_dict={X: x_data, Y: y_data}))
print('accuracy:', sess.run(accuracy, feed_dict={X: x_data, Y: y_data}))
# print 'accuracy:', accuracy.eval({X: x_data, Y: y_data})

[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]
[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]]
0 0.705415 [[-0.60277987  0.84521204  0.59893084 -0.49067473  0.82905155]
 [ 0.88983375 -0.65611529 -0.84023666 -0.54103112 -0.71363848]] [[ -9.81755205e-04  -9.05598402e-01  -5.26907444e-02  -1.19380951e-01
   -9.97609854e-01]
 [  7.78688014e-01  -6.95781708e-02  -6.92106247e-01  -1.80536509e-01
   -1.61870718e-01]
 [  8.71614218e-01   1.83330774e-01   3.82869244e-02   9.68306303e-01
   -5.43785810e-01]
 [ -6.22396469e-01   3.49048615e-01   7.98421621e-01   7.89460182e-01
    7.03926802e-01]
 [  5.80230653e-01  -3.67656946e-01   4.68454599e-01  -5.40303230e-01
    6.71741247e-01]]
200 0.501835 [[-0.62373286  0.92274791  0.59893084 -0.49067473  0.89048439]
 [ 1.02960348 -0.92800921 -0.84023666 -0.54103112 -0.78596687]] [[-0.44729319 -0.9055984  -0.05269074 -0.11938095 -0.99760985]
 [ 1.05926621 -0.06957817 -0.69210625 -0.18053651 -0.16187072]
 [ 0.87161422  0.18333077  0.03828692  0.9683063  -0.54378581]
 [-0.622

In [2]:
import tensorflow as tf
import numpy as np
import os

# script_dir = os.path.dirname(os.path.abspath(__file__))
script_dir = os.getcwd()
train_data = np.loadtxt(script_dir + '/data/NeuralNetwork.txt', unpack=True, dtype='float')
x_data = np.transpose(train_data[0:-1])
y_data = np.reshape(train_data[-1:], (4, 1))

print(x_data)
print(y_data)

X = tf.placeholder(tf.float32, name='x-input')
Y = tf.placeholder(tf.float32, name='y-input')

with tf.name_scope('weight') as scope:
    W1 = tf.Variable(tf.random_uniform([2, 5], -1., 1.), name='weight1')
    W2 = tf.Variable(tf.random_uniform([5, 5], -1., 1.), name='weight2')
    W3 = tf.Variable(tf.random_uniform([5, 4], -1., 1.), name='weight3')
    W4 = tf.Variable(tf.random_uniform([4, 1], -1., 1.), name='weight4')

with tf.name_scope('bias') as scope:
    b1 = tf.Variable(tf.random_uniform([5], -1., 1.), name='bias1')
    b2 = tf.Variable(tf.random_uniform([5], -1., 1.), name='bias2')
    b3 = tf.Variable(tf.random_uniform([4], -1., 1.), name='bias3')
    b4 = tf.Variable(tf.random_uniform([1], -1., 1.), name='bias4')

with tf.name_scope('layer2') as scope:
    L2 = tf.nn.relu(tf.matmul(X, W1) + b1)
with tf.name_scope('layer3') as scope:
    L3 = tf.nn.relu(tf.matmul(L2, W2) + b2)
with tf.name_scope('layer4') as scope:
    L4 = tf.nn.relu(tf.matmul(L3, W3) + b3)

with tf.name_scope('hypothesis') as scope:
    hypothesis = tf.sigmoid(tf.matmul(L4, W4) + b4)

with tf.name_scope('cost') as scope:
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
    cost_sum = tf.summary.scalar('cost', cost)

w1_hist_sum = tf.summary.histogram('weight1', W1)
w2_hist_sum = tf.summary.histogram('weight2', W2)
w3_hist_sum = tf.summary.histogram('weight3', W3)
w4_hist_sum = tf.summary.histogram('weight4', W4)

b1_hist_sum = tf.summary.histogram('bias1', b1)
b2_hist_sum = tf.summary.histogram('bias2', b2)
b3_hist_sum = tf.summary.histogram('bias3', b3)
b4_hist_sum = tf.summary.histogram('bias4', b4)

y_hist_sum = tf.summary.histogram('y', Y)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)

    learning_rate = 0.1
    optimizer = tf.train.GradientDescentOptimizer(learning_rate)
    train = optimizer.minimize(cost)

    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter('logs/xor_logs', sess.graph)

    for step in range(10000):
        sess.run(train, feed_dict={X: x_data, Y: y_data})

        if step % 200 == 0:
            summary = sess.run(merged, feed_dict={X: x_data, Y:y_data})
            writer.add_summary(summary, step)
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W1), sess.run(W2))

    correct_prediction = tf.equal(tf.floor(hypothesis + 0.5), Y)

    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    print(sess.run([hypothesis, tf.floor(hypothesis + 0.5), correct_prediction], feed_dict={X: x_data, Y: y_data}))
    print('accuracy:', sess.run(accuracy, feed_dict={X: x_data, Y: y_data}))
    # print 'accuracy:', accuracy.eval({X: x_data, Y: y_data})

[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]
[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]]
0 0.686351 [[-0.03026772  0.43204212 -0.79715008 -0.37047985 -0.31084967]
 [-0.36049795  0.87844974  0.69809479 -0.64086747 -0.05124855]] [[-0.12832689  0.04537797 -0.47097731 -0.81130028  0.59517026]
 [ 0.78401923  0.54358858 -0.41292143 -0.08893812 -0.99660414]
 [-0.85437316  0.86371613 -0.21483207  0.61969584 -0.22288108]
 [ 0.48823988 -0.75866735 -0.19706416  0.80796576 -0.39218587]
 [-0.24446607  0.8511579  -0.01615763 -0.92114639  0.39036202]]
200 0.0380093 [[-0.03026772  0.39808732 -1.52040148 -1.00051367 -0.31084967]
 [-0.36049795  1.23942065  0.73791677 -0.9979592  -0.05124855]] [[-0.12832689  0.04537797 -0.47097731 -0.81130028  0.59517026]
 [ 1.21073925  0.44055089 -0.41292143 -0.20569664 -0.99354368]
 [-0.82507998  1.44877577 -0.21483207  0.78511339 -0.57560962]
 [ 0.76414257 -0.75371164 -0.19706416  1.22071636 -0.68658924]
 [-0.24446607  0.8511579  -0.01615763 -0.92114639  0.39036202]]
400 0.00784457 