Activation 함수 중 시그모이드 함수

In [11]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)


In [26]:
import numpy as np

arr = np.arange(9).reshape(3,3)
rarr = np.random.shuffle(arr)
# print(arr)

input_node_num = 3

# input_vector for training
test_data = np.random.randint(5, size=(10,input_node_num))

# test_data = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])

row_num = 5
col_num = 3

weighted_hidden_layer_list = [3, 5, 4, 7, 3]
hidden_layer_num = len(weighted_hidden_layer_list)


# print(np.random.random((1,1)))

print(np.random.randn())

weighted_matrix = [np.random.random((node_num, input_node_num)) for node_num in weighted_hidden_layer_list]
print(weighted_matrix)

def feed_forward(test_matrix, weighted_matrix):
    for matx in weighted_matrix:
        multiplied_matrix = np.matmul(matx, test_matrix)
        print(np.array([multiplied_matrix]))
        transposed_multi_mat = np.array([multiplied_matrix]).transpose()
        print(transposed_multi_mat)
        print(transposed_multi_mat.shape)
        bias_vector = np.random.random((1, transposed_multi_mat.shape[0]))
        print(bias_vector.transpose())

        result_matrix = np.append(transposed_multi_mat, bias_vector.transpose(), axis=1)
        print(result_matrix)

feed_forward([6,2,0], weighted_matrix)

# print(w_matrix)

# print(b)

0.5749485705148473
[array([[ 0.31637619,  0.99006539,  0.9554376 ],
       [ 0.78082272,  0.97683912,  0.7931988 ],
       [ 0.47395772,  0.08257653,  0.87764375]]), array([[ 0.82112515,  0.41225687,  0.94178766],
       [ 0.98642645,  0.60953771,  0.13153211],
       [ 0.2974485 ,  0.98957531,  0.6252349 ],
       [ 0.30275913,  0.49237772,  0.05859657],
       [ 0.16086414,  0.78041324,  0.04475936]]), array([[ 0.52599268,  0.15256782,  0.73394358],
       [ 0.98864265,  0.28407043,  0.30118226],
       [ 0.73863403,  0.45057995,  0.22154054],
       [ 0.89814545,  0.95008538,  0.82128135]]), array([[ 0.20373785,  0.50081025,  0.51294346],
       [ 0.2593736 ,  0.7638434 ,  0.17008834],
       [ 0.68372869,  0.64319765,  0.52941152],
       [ 0.55682676,  0.62148461,  0.83649128],
       [ 0.10875482,  0.58488943,  0.98660174],
       [ 0.69732438,  0.01353448,  0.63700806],
       [ 0.50196042,  0.24488538,  0.44355613]]), array([[ 0.2100422 ,  0.80644759,  0.49201118],
       [ 0.8

In [6]:
import numpy as np

input_node_num = 3

# input_vector for training
test_data = np.random.randint(9, size=(10,input_node_num))

# test_data = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])

# train function
def train(test_data):
    for td in test_data:
        print(td)
        transpoed_td = td.reshape((-1, 1))
        
train(test_data)

[6 2 0]
[7 5 7]
[8 8 6]
[3 2 4]
[8 8 6]
[1 8 2]
[3 3 0]
[7 0 6]
[2 4 6]
[6 1 1]


In [82]:
import numpy as np

# np.random.random(3, np.random.randint(3,6))

x = np.ones((1, 1, 3))
print(x.transpose())
print( np.transpose(x, (1,3,0)) )

a = np.arange(6).reshape(2,3)
print(a)
print(len([1,2,3]))

[[[ 1.]]

 [[ 1.]]

 [[ 1.]]]


AxisError: axis 3 is out of bounds for array of dimension 3